### ISSUE TITLE
Just an hint - sleep is supposed to work under Linux

### ISSUE THREAD

**Issue by Anycubic** [Forte500/ERYING-i9-11900H-ES-Hackintosh#1]
I watched a video on Youtube  where they say sleep is working fine under Linux, so maybe it's something fixable. In Windows hibernation works fine, didn't check with MacOS actually.

**Comment by Forte500** [comment]
Hi, Would you please link me the video?
Also, is it an ES or non-ES SKU?

**Comment by Anycubic** [comment]
@Forte500 https://youtu.be/_0zCEhRmDQE he is saying sleep is working at around 10:10.
It seems to me it is an ES board, like yours and mine

**Comment by Forte500** [comment]
@Anycubic unfortunately it doesn't seem to work, tested with manjaro 23.1.0.
I'm gonna try to reflash the stock bios to see if anything changes.
Did you also tested if sleep works under linux? Let me know

**Comment by Forte500** [comment]
@Anycubic Since I haven't received any further news from you, I will go ahead and close the issue. If you have any other information, feel free to comment.
